### ISSUE TITLE
Monitoring network

### ISSUE THREAD

**Issue by quynhvuongg** [quynhvuongg/Prometheus#12]
# Monitoring Network

## Các tiêu chí giám sát mạng trên host

* Độ khả dụng của máy chủ như CPU,memory,disk,...

* Độ khả dụng của các thiết bị mạng(router,switch,...) như CPU, memory, interfaces,...

* Độ khả dụng của đường truyền như tốc độ lưu lượng, thông lượng,lỗi, các kết nối như TCP,UDP,ICMP,IP,... (in,out,error)

### 1. Độ khả dụng của máy chủ

![image](https://user-images.githubusercontent.com/61721493/80577664-750c6a80-8a31-11ea-9e3b-da8ec52fd297.png)

**_CPU_**

*_Node-exporter_*

* node_cpu_second_total

![image](https://user-images.githubusercontent.com/61721493/80576862-1f838e00-8a30-11ea-9334-847704f64bbe.png)

*_Cadvisor_*

* container_cpu_load_average_10s
* container_cpu_system_seconds_total
* container_cpu_usage_seconds_total

**_Memory_**

*_Node-exporter_*

* node_memory_MemTotal_bytes
* node_memory_MemAvailable_bytes
* node_memory_MemFree_bytes
* node_memory_Active_bytes
* node_memory_Inactive_bytes
* node_memory_Cached_bytes
* node_memory_Buffers_bytes
* node_memory_SwapTotal_bytes
* node_memory_SwapFree_bytes
* node_memory_SwapCached_bytes

![image](https://user-images.githubusercontent.com/61721493/80577451-1a730e80-8a31-11ea-8d67-d1da62d22322.png)
  
*_Cadvisor_*

* container_memory_usage_bytes
* container_memory_swap
* container_memory_cache

**_Disk_**

*_Node-exporter_*

* node_disk_discard_time_seconds_total
* node_disk_discarded_sectors_total
* node_disk_discards_completed_total
* node_disk_discards_merged_total
* node_disk_io_now
* node_disk_io_time_seconds_total
* node_disk_read_bytes_total
* node_disk_read_time_seconds_total
* node_disk_reads_completed_total
* node_disk_reads_merged_total
* node_disk_written_bytes_total
* node_disk_write_time_seconds_total
* node_disk_writes_completed_total
* node_disk_writes_merged_total

![image](https://user-images.githubusercontent.com/61721493/80577785-adac4400-8a31-11ea-972d-13bafae65dce.png)

...

### 2. Độ khả dụng của các thiết bị mạng

SNMP-exporter (Router)

**_cpu_usage1min:_** `1.3.6.1.4.1.9.9.109.1.1.1.1.7`

**_memomry_usage:_** `1.3.6.1.4.1.9.9.48.1.1.1.5`

**_list_port:_** `1.3.6.1.2.1.17.1.4.1.2 (ifIndex)`

**_port_traffic:_**

* `1.3.6.1.2.1.2.2.1.10 (ifInOctets)`
* `1.3.6.1.2.1.2.2.1.16 (ifOutOctets)`

**_port_speed:_** `1.3.6.1.2.1.2.2.1.5 (ifSpeed)`

**_description_interfaces:_** `1.3.6.1.2.1.2.2.1.2 (ifDescr)`

**_packet_error:_**

* `1.3.6.1.2.1.2.2.1.20 (ifOutErrors)`
* `1.3.6.1.2.1.2.2.1.20 (ifInErrors)`

...

### 3. Độ khả dụng của đường truyền

Node-exporter

**_Network speed:_**

* node_network_speed_bytes

**_Network traffic:_**

* node_network_transmit_bytes_total
* node_network_transmit_drop_total
* node_network_transmit_errs_total
* node_network_transmit_packets_total

* node_network_receive_bytes_total
* node_network_receive_carrier_total
* node_network_receive_drop_total
* node_network_receive_errs_total
* node_network_receive_packets_total
* node_network_receive_frame_total

![image](https://user-images.githubusercontent.com/61721493/80578029-14c9f880-8a32-11ea-8f81-5a484f986219.png)

![image](https://user-images.githubusercontent.com/61721493/80578065-227f7e00-8a32-11ea-84e6-f00d61b1cf70.png)

* node_network_transmit_carrier_total
* node_network_carrier_up_changes_total
* node_network_carrier_down_changes_total

**_Network mtu:_**

* node_network_mtu_bytes

**_Network Socket:_**

* node_sockstat_sockets_used

* node_sockstat_TCP_alloc
* node_sockstat_TCP_inuse
* node_sockstat_TCP_mem
* node_sockstat_TCP_mem_bytes
* node_sockstat_TCP_orphan
* node_sockstat_TCP_tw

* node_sockstat_UDPLITE_inuse
* node_sockstat_UDPLITE_inuse
* node_sockstat_UDP_mem
* node_sockstat_UDP_mem_bytes

![image](https://user-images.githubusercontent.com/61721493/80578230-578bd080-8a32-11ea-812a-3c7b2847c8df.png)

**_Network Static:_**

* node_netstat_Icmp_InMsgs
* node_netstat_Icmp_OutMsgs
* node_netstat_Icmp_InErrors

* node_netstat_IpExt_InOctets
* node_netstat_IpExt_OutOctets

* node_netstat_Tcp_InSegs
* node_netstat_Tcp_OutSegs
* node_netstat_Tcp_InErrs
* node_netstat_Tcp_ActiveOpens
* node_netstat_Tcp_PassiveOpens
* node_netstat_Tcp_RetransSegs
* node_netstat_TcpExt_ListenDrops
* node_netstat_TcpExt_ListenOverflows
* node_netstat_TcpExt_SyncookiesFailed
* node_netstat_TcpExt_SyncookiesRecv
* node_netstat_TcpExt_SyncookiesSent
* node_netstat_TcpExt_TCPSynRetrans
  
![image](https://user-images.githubusercontent.com/61721493/80578338-8144f780-8a32-11ea-87ab-84c52eda444d.png)

![image](https://user-images.githubusercontent.com/61721493/80578538-ccf7a100-8a32-11ea-8b27-da55ac64e221.png)

* node_netstat_Udp_InDatagrams
* node_netstat_Udp_OutDatagrams
* node_netstat_Udp_InErrors

## Alert rules

1. Bộ nhớ sắp đầy ( dung lượng có sẵn < 20%)

```yml
- alert: HostOutOfMemory
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 20
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host out of memory (instance {{ $labels.instance }})"
      description: "Node memory is filling up (< 20% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

```

```yml
 - alert: ContainerMemoryUsage
    expr: (sum(container_memory_usage_bytes) BY (instance, name) / sum(container_spec_memory_limit_bytes) BY (instance, name) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Container Memory usage (instance {{ $labels.instance }})"
      description: "Container Memory usage is above 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

```

2. CPU cao (> 80%)

```yml
- alert: HostHighCpuLoad
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host high CPU load (instance {{ $labels.instance }})"
      description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

```yml

  - alert: ContainerCpuUsage
    expr: (sum(rate(container_cpu_usage_seconds_total[3m])) BY (instance, name) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Container CPU usage (instance {{ $labels.instance }})"
      description: "Container CPU usage is above 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

3. Disk đọc quá nhiều dữ liệu (> 50Mb/s)

```yml
- alert: HostUnusualDiskReadRate
    expr: sum by (instance) (irate(node_disk_read_bytes_total[2m])) / 1024 / 1024 > 50
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host unusual disk read rate (instance {{ $labels.instance }})"
      description: "Disk is probably reading too much data (> 50 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

```

4. Disk ghi quá nhiều dữ liệu (> 50Mb/s)

```yml
 - alert: HostUnusualDiskWriteRate
    expr: sum by (instance) (irate(node_disk_written_bytes_total[2m])) / 1024 / 1024 > 50
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host unusual disk write rate (instance {{ $labels.instance }})"
      description: "Disk is probably writing too much data (> 50 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

```

5. Không gian Disk sắp đầy

```yml
  - alert: HostOutOfDiskSpace
    expr: (node_filesystem_avail_bytes{mountpoint="/rootfs"}  * 100) / node_filesystem_size_bytes{mountpoint="/rootfs"} < 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host out of disk space (instance {{ $labels.instance }})"
      description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

```

6. Thông lượng vào lớn (> 100 Mb/s)

```yml
 - alert: HostUnusualNetworkThroughputIn
    expr: sum by (instance) (irate(node_network_receive_bytes_total[2m])) / 1024 / 1024 > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host unusual network throughput in (instance {{ $labels.instance }})"
      description: "Host network interfaces are probably receiving too much data (> 100 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

```

7. Thông lượng ra lớn  (> 100Mb/s)

```yml
 - alert: HostUnusualNetworkThroughputOut
    expr: sum by (instance) (irate(node_network_transmit_bytes_total[2m])) / 1024 / 1024 > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host unusual network throughput out (instance {{ $labels.instance }})"
      description: "Host network interfaces are probably sending too much data (> 100 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

```

8. Socket

9. Netstat

10. SNMP
