### ISSUE TITLE
Task 1

### ISSUE THREAD

**Issue by quynhvuongg** [quynhvuongg/Prometheus#9]
Đây là phần code hiện tại của em ạ :

```yml
#dockercompose.yml
version: '3.7'

volumes:
  prometheus_data: {}

services: 
 
  prometheus1: 
    image: prom/prometheus
    container_name: prometheus1
    volumes:  
      - ./prometheus1.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus1
      - ./rule_files:/etc/prometheus/rule_files
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.listen-address=127.0.0.1:9090"
    ports:     
      - 9090:9090

  prometheus2: 
    image: prom/prometheus
    container_name: prometheus2
    volumes:  
      - ./prometheus2.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus2
      - ./rule_files:/etc/prometheus/rule_files
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.listen-address=127.0.0.1:9091"
    ports:     
      - 9091:9091
    
  alertmanager1:
    image: prom/alertmanager
    container_name: alertmanager1
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--web.listen-address=:9093"
      - "--cluster.listen-address=127.0.0.1:8001"
      - "--cluster.peer=127.0.0.1:8001"
      - "--log.level=debug"
    ports:
      - 9093:9093
 
  alertmanager2:
    image: prom/alertmanager
    container_name: alertmanager2
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--web.listen-address=:9094"
      - "--cluster.listen-address=127.0.0.1:8002"
      - "--cluster.peer=127.0.0.1:8001"
      - "--log.level=debug"

    ports:
      - 9094:9094

```

```yml
#prometheus.yml
global:  
  scrape_interval:  15s   
  external_labels: 
      dc: 'node1' 

scrape_configs:  
      - job_name: 'prometheus'  
        static_configs: 
             - targets: ['127.0.0.1:9090']

      

rule_files:  
  - "rule_files"

alerting:
  alert_relabel_configs:
    - source_labels: [dc]
      regex: (.+)\d+
      target_label: dc
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 127.0.0.1:9093
      - 127.0.0.1:9094

```

Khi cho run em gặp một số lỗi 

1. Hai con Prometheus của em có vẻ run bình thường không báo lỗi trên log nhưng khi em vào localhost:9090 hay 9091 đều không được 

![ ](https://github.com/quynhvuongg/Picture/blob/master/ero5.png?raw=true)

![ ](https://github.com/quynhvuongg/Picture/blob/master/ero4.png?raw=true)

2. Alertmanager 1,2 của em thì vào được nhưng chưa call nhau đc

![image](https://user-images.githubusercontent.com/61721493/80192531-89232700-8641-11ea-9103-bce9d7fed4ee.png)

![image](https://user-images.githubusercontent.com/61721493/80192581-9a6c3380-8641-11ea-97d6-989ba6631e8c.png)

![ ](https://github.com/quynhvuongg/Picture/blob/master/ero1.png?raw=true)

![ ](https://github.com/quynhvuongg/Picture/blob/master/ero2.png?raw=true)

![image](https://user-images.githubusercontent.com/61721493/80192259-1d40be80-8641-11ea-93cb-01fad16f37f2.png)

tường lửa của em ko có bật ạ.
